"""
PDF export module — generates a downloadable error report using fpdf2.
"""

from datetime import date
from fpdf import FPDF
from src.correction import CorrectionResult


def _sanitize(text: str) -> str:
    """Replace Unicode characters outside Latin-1 (Helvetica range) with ASCII equivalents."""
    return (
        text
        .replace("‘", "'").replace("’", "'")    # curly single quotes / apostrophe
        .replace("“", '"').replace("”", '"')    # curly double quotes
        .replace("–", "-").replace("—", "-")    # en dash / em dash
        .replace("…", "...").replace("•", "*")  # ellipsis / bullet
        .replace("œ", "oe").replace("Œ", "OE")  # œ / Œ  (French ligature)
        .replace("æ", "ae").replace("Æ", "AE")  # æ / Æ
        .replace("€", "EUR").replace("£", "GBP")  # currency symbols
    )


_TYPE_LABELS = {
    "spelling":     "Spelling",
    "grammar":      "Grammar",
    "accent":       "Accent",
    "missing_word": "Missing word",
    "extra_word":   "Extra word",
}


def generate_pdf(
    correction: CorrectionResult,
    student_name: str,
    correct_text: str,
) -> bytes:
    """Return PDF bytes for a correction result."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Header ────────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "LacDictee - Error Report", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f"Student: {_sanitize(student_name or 'Unknown')}    Date: {date.today().isoformat()}", ln=True)
    pdf.ln(3)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_text_color(0, 0, 0)

    # ── Reference text ────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Reference text", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, _sanitize(correct_text))
    pdf.ln(3)

    # ── Score summary ─────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Score", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(60, 6, f"Score:         {correction.score} / 100")
    pdf.cell(60, 6, f"Errors found:  {correction.error_count}")
    pdf.cell(60, 6, f"Total words:   {correction.total_words}", ln=True)
    pdf.ln(3)

    # ── Error type breakdown ──────────────────────────────────────────────────
    if correction.errors_by_type:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, "Error breakdown", ln=True)
        pdf.set_font("Helvetica", "", 10)
        for etype, count in correction.errors_by_type.items():
            label = _TYPE_LABELS.get(etype, etype)
            pdf.cell(0, 6, f"  {label}: {count}", ln=True)
        pdf.ln(3)

    # ── Error list ────────────────────────────────────────────────────────────
    if correction.errors:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, "Errors", ln=True)
        pdf.ln(1)

        for i, err in enumerate(correction.errors, 1):
            label = _TYPE_LABELS.get(err.type, err.type)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, f"{i}. {_sanitize(err.wrong)}  ->  {_sanitize(err.correct)}  ({label})", ln=True)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(0, 5, f"   {_sanitize(err.explanation)}")
            pdf.set_text_color(0, 0, 0)
            pdf.ln(1)
    else:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(0, 150, 0)
        pdf.cell(0, 7, "Perfect dictation! No errors found.", ln=True)
        pdf.set_text_color(0, 0, 0)

    # ── Footer ────────────────────────────────────────────────────────────────
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(160, 160, 160)
    pdf.cell(0, 5, "Generated by LacDictee - AI-powered French dictation correction", align="C")

    return bytes(pdf.output())
